## Eigenvalues

In [1]:
# !pip install ipywidgets

In [1]:
from build_dataset import build_dataset
from analyze import run_analysis
from analyze import leave_one_out
from analyze import leave_two_out
import pandas as pd

### Create datasets

In [2]:
build_dataset(attn_root="outputs/attentions/", output_csv="results/eigen_eng_other.csv", mode=1, topk=12, limit_per_pair=None, overwrite=False)

Dataset already exists at results/eigen_eng_other.csv. Use --overwrite to rebuild.

In [3]:
build_dataset(attn_root="outputs/attentions/", output_csv="results/eigen_other_eng.csv", mode=2, topk=12, limit_per_pair=None, overwrite=False)

Dataset already exists at results/eigen_other_eng.csv. Use --overwrite to rebuild.

### Run analysis

In [3]:
df = pd.read_csv("results/eigen_eng_other.csv")
run_analysis(df, output_dir="results/eng_other", n_splits=5, seeds=[42, 1, 2], name="eigen_eng_other")

Detected: 24 layers × 16 heads
Dataset: 21934 samples, class balance: [10967 10967]

[1/4] Full features
  acc = 0.9998 ± 0.0002

[2/4] Per-layer
  L00: 0.8827 ± 0.0059
  L01: 0.8570 ± 0.0071
  L02: 0.9119 ± 0.0037
  L03: 0.9488 ± 0.0025
  L04: 0.9586 ± 0.0038
  L05: 0.9544 ± 0.0039
  L06: 0.9386 ± 0.0042
  L07: 0.9533 ± 0.0028
  L08: 0.9458 ± 0.0036
  L09: 0.9584 ± 0.0025
  L10: 0.9633 ± 0.0022
  L11: 0.9779 ± 0.0025
  L12: 0.9299 ± 0.0024
  L13: 0.9346 ± 0.0028
  L14: 0.8755 ± 0.0040
  L15: 0.9274 ± 0.0032
  L16: 0.9239 ± 0.0042
  L17: 0.8544 ± 0.0053
  L18: 0.8292 ± 0.0048
  L19: 0.8317 ± 0.0067
  L20: 0.8596 ± 0.0049
  L21: 0.8207 ± 0.0060
  L22: 0.7940 ± 0.0074
  L23: 0.8287 ± 0.0040

[3/4] Per-head
  H00: 0.9408 ± 0.0036
  H01: 0.9550 ± 0.0036
  H02: 0.9697 ± 0.0019
  H03: 0.9882 ± 0.0019
  H04: 0.9527 ± 0.0034
  H05: 0.9531 ± 0.0024
  H06: 0.9638 ± 0.0024
  H07: 0.9454 ± 0.0033
  H08: 0.9567 ± 0.0028
  H09: 0.9678 ± 0.0026
  H10: 0.9551 ± 0.0025
  H11: 0.9291 ± 0.0046
  H12: 0.9786 ± 0.0023
  H13: 0.9128 ± 0.0045
  H14: 0.9099 ± 0.0044
  H15: 0.9553 ± 0.0029

[4/4] Heatmap (24×16 = 384 probes)
  Layer 00 done
  Layer 01 done
  Layer 02 done
  Layer 03 done
  Layer 04 done
  Layer 05 done
  Layer 06 done
  Layer 07 done
  Layer 08 done
  Layer 09 done
  Layer 10 done
  Layer 11 done
  Layer 12 done
  Layer 13 done
  Layer 14 done
  Layer 15 done
  Layer 16 done
  Layer 17 done
  Layer 18 done
  Layer 19 done
  Layer 20 done
  Layer 21 done
  Layer 22 done
  Layer 23 done

All outputs saved to results/eng_other/

In [4]:
df = pd.read_csv("results/eigen_other_eng.csv")
run_analysis(df, output_dir="results/other_eng", n_splits=5, seeds=[42, 1, 2], name="eigen_other_eng")

Detected: 24 layers × 16 heads
Dataset: 21934 samples, class balance: [10967 10967]

[1/4] Full features
  acc = 0.9187 ± 0.0053

[2/4] Per-layer
  L00: 0.7188 ± 0.0057
  L01: 0.7230 ± 0.0051
  L02: 0.6737 ± 0.0047
  L03: 0.7095 ± 0.0065
  L04: 0.7318 ± 0.0063
  L05: 0.7428 ± 0.0077
  L06: 0.6944 ± 0.0065
  L07: 0.6664 ± 0.0056
  L08: 0.6923 ± 0.0073
  L09: 0.6475 ± 0.0054
  L10: 0.6395 ± 0.0090
  L11: 0.6577 ± 0.0055
  L12: 0.6369 ± 0.0093
  L13: 0.6323 ± 0.0089
  L14: 0.6672 ± 0.0054
  L15: 0.6345 ± 0.0078
  L16: 0.6410 ± 0.0059
  L17: 0.6222 ± 0.0081
  L18: 0.6866 ± 0.0066
  L19: 0.6294 ± 0.0067
  L20: 0.6356 ± 0.0084
  L21: 0.6159 ± 0.0069
  L22: 0.6638 ± 0.0071
  L23: 0.6590 ± 0.0075

[3/4] Per-head
  H00: 0.6985 ± 0.0076
  H01: 0.6993 ± 0.0062
  H02: 0.6994 ± 0.0045
  H03: 0.7063 ± 0.0046
  H04: 0.7495 ± 0.0048
  H05: 0.7245 ± 0.0064
  H06: 0.6831 ± 0.0075
  H07: 0.7527 ± 0.0061
  H08: 0.7126 ± 0.0063
  H09: 0.6662 ± 0.0047
  H10: 0.6921 ± 0.0071
  H11: 0.7230 ± 0.0056
  H12: 0.7600 ± 0.0047
  H13: 0.7092 ± 0.0046
  H14: 0.6944 ± 0.0067
  H15: 0.7063 ± 0.0067

[4/4] Heatmap (24×16 = 384 probes)
  Layer 00 done
  Layer 01 done
  Layer 02 done
  Layer 03 done
  Layer 04 done
  Layer 05 done
  Layer 06 done
  Layer 07 done
  Layer 08 done
  Layer 09 done
  Layer 10 done
  Layer 11 done
  Layer 12 done
  Layer 13 done
  Layer 14 done
  Layer 15 done
  Layer 16 done
  Layer 17 done
  Layer 18 done
  Layer 19 done
  Layer 20 done
  Layer 21 done
  Layer 22 done
  Layer 23 done

All outputs saved to results/other_eng/

In [5]:
df = pd.read_csv("results/eigen_eng_other.csv")
leave_two_out(df, output_dir="results/eng_other_lto", name="eigen_eng_other_lto", seed=42, lang_col="tgt_lang")

Leave-two-out: 121 combinations, lang_col='tgt_lang'
  SVO=fra  SOV=jpn : acc=0.9975
  SVO=fra  SOV=kor : acc=1.0000
  SVO=fra  SOV=tur : acc=1.0000
  SVO=fra  SOV=pes : acc=0.5797
  SVO=fra  SOV=hin : acc=1.0000
  SVO=fra  SOV=kat : acc=0.8962
  SVO=fra  SOV=tam : acc=1.0000
  SVO=fra  SOV=aze : acc=1.0000
  SVO=fra  SOV=khk : acc=1.0000
  SVO=fra  SOV=urd : acc=1.0000
  SVO=fra  SOV=ben : acc=1.0000
  SVO=deu  SOV=jpn : acc=0.9965
  SVO=deu  SOV=kor : acc=1.0000
  SVO=deu  SOV=tur : acc=1.0000
  SVO=deu  SOV=pes : acc=0.5827
  SVO=deu  SOV=hin : acc=1.0000
  SVO=deu  SOV=kat : acc=0.8721
  SVO=deu  SOV=tam : acc=1.0000
  SVO=deu  SOV=aze : acc=1.0000
  SVO=deu  SOV=khk : acc=1.0000
  SVO=deu  SOV=urd : acc=1.0000
  SVO=deu  SOV=ben : acc=1.0000
  SVO=tha  SOV=jpn : acc=0.8541
  SVO=tha  SOV=kor : acc=0.8671
  SVO=tha  SOV=tur : acc=0.7768
  SVO=tha  SOV=pes : acc=0.5416
  SVO=tha  SOV=hin : acc=0.7994
  SVO=tha  SOV=kat : acc=0.9604
  SVO=tha  SOV=tam : acc=0.8164
  SVO=tha  SOV=aze : acc=0.6419
  SVO=tha  SOV=khk : acc=0.8315
  SVO=tha  SOV=urd : acc=0.8144
  SVO=tha  SOV=ben : acc=0.8275
  SVO=ind  SOV=jpn : acc=0.9970
  SVO=ind  SOV=kor : acc=1.0000
  SVO=ind  SOV=tur : acc=1.0000
  SVO=ind  SOV=pes : acc=0.5787
  SVO=ind  SOV=hin : acc=1.0000
  SVO=ind  SOV=kat : acc=0.8937
  SVO=ind  SOV=tam : acc=1.0000
  SVO=ind  SOV=aze : acc=1.0000
  SVO=ind  SOV=khk : acc=1.0000
  SVO=ind  SOV=urd : acc=1.0000
  SVO=ind  SOV=ben : acc=1.0000
  SVO=zho  SOV=jpn : acc=0.6429
  SVO=zho  SOV=kor : acc=0.6043
  SVO=zho  SOV=tur : acc=0.5838
  SVO=zho  SOV=pes : acc=0.4569
  SVO=zho  SOV=hin : acc=0.6264
  SVO=zho  SOV=kat : acc=0.4152
  SVO=zho  SOV=tam : acc=0.6204
  SVO=zho  SOV=aze : acc=0.2728
  SVO=zho  SOV=khk : acc=0.5968
  SVO=zho  SOV=urd : acc=0.5983
  SVO=zho  SOV=ben : acc=0.6103
  SVO=rus  SOV=jpn : acc=0.9950
  SVO=rus  SOV=kor : acc=0.9970
  SVO=rus  SOV=tur : acc=0.9965
  SVO=rus  SOV=pes : acc=0.5903
  SVO=rus  SOV=hin : acc=0.9970
  SVO=rus  SOV=kat : acc=0.9253
  SVO=rus  SOV=tam : acc=0.9930
  SVO=rus  SOV=aze : acc=0.9890
  SVO=rus  SOV=khk : acc=0.9960
  SVO=rus  SOV=urd : acc=0.9975
  SVO=rus  SOV=ben : acc=0.9965
  SVO=vie  SOV=jpn : acc=0.9975
  SVO=vie  SOV=kor : acc=1.0000
  SVO=vie  SOV=tur : acc=1.0000
  SVO=vie  SOV=pes : acc=0.5692
  SVO=vie  SOV=hin : acc=1.0000
  SVO=vie  SOV=kat : acc=0.8912
  SVO=vie  SOV=tam : acc=1.0000
  SVO=vie  SOV=aze : acc=1.0000
  SVO=vie  SOV=khk : acc=1.0000
  SVO=vie  SOV=urd : acc=1.0000
  SVO=vie  SOV=ben : acc=1.0000
  SVO=por  SOV=jpn : acc=0.9970
  SVO=por  SOV=kor : acc=1.0000
  SVO=por  SOV=tur : acc=1.0000
  SVO=por  SOV=pes : acc=0.5717
  SVO=por  SOV=hin : acc=1.0000
  SVO=por  SOV=kat : acc=0.8947
  SVO=por  SOV=tam : acc=1.0000
  SVO=por  SOV=aze : acc=1.0000
  SVO=por  SOV=khk : acc=1.0000
  SVO=por  SOV=urd : acc=1.0000
  SVO=por  SOV=ben : acc=1.0000
  SVO=swh  SOV=jpn : acc=0.8420
  SVO=swh  SOV=kor : acc=0.8275
  SVO=swh  SOV=tur : acc=0.8771
  SVO=swh  SOV=pes : acc=0.5396
  SVO=swh  SOV=hin : acc=0.8666
  SVO=swh  SOV=kat : acc=0.7337
  SVO=swh  SOV=tam : acc=0.8606
  SVO=swh  SOV=aze : acc=0.8516
  SVO=swh  SOV=khk : acc=0.8756
  SVO=swh  SOV=urd : acc=0.7914
  SVO=swh  SOV=ben : acc=0.8320
  SVO=fin  SOV=jpn : acc=0.6389
  SVO=fin  SOV=kor : acc=0.6665
  SVO=fin  SOV=tur : acc=0.6545
  SVO=fin  SOV=pes : acc=0.2452
  SVO=fin  SOV=hin : acc=0.6605
  SVO=fin  SOV=kat : acc=0.7859
  SVO=fin  SOV=tam : acc=0.6585
  SVO=fin  SOV=aze : acc=0.3651
  SVO=fin  SOV=khk : acc=0.6449
  SVO=fin  SOV=urd : acc=0.6625
  SVO=fin  SOV=ben : acc=0.6740
  SVO=swe  SOV=jpn : acc=0.9975
  SVO=swe  SOV=kor : acc=1.0000
  SVO=swe  SOV=tur : acc=1.0000
  SVO=swe  SOV=pes : acc=0.5767
  SVO=swe  SOV=hin : acc=1.0000
  SVO=swe  SOV=kat : acc=0.8641
  SVO=swe  SOV=tam : acc=1.0000
  SVO=swe  SOV=aze : acc=1.0000
  SVO=swe  SOV=khk : acc=1.0000
  SVO=swe  SOV=urd : acc=1.0000
  SVO=swe  SOV=ben : acc=1.0000

Overall LTO: 0.8557 ± 0.1873
Saved LTO results to results/eng_other_lto/

     held_svo  held_sov     acc  n_train  n_test
0    fra_Latn  jpn_Jpan  0.9975    19940    1994
1    fra_Latn  kor_Hang  1.0000    19940    1994
2    fra_Latn  tur_Latn  1.0000    19940    1994
3    fra_Latn  pes_Arab  0.5797    19940    1994
4    fra_Latn  hin_Deva  1.0000    19940    1994
..        ...       ...     ...      ...     ...
116  swe_Latn  tam_Taml  1.0000    19940    1994
117  swe_Latn  aze_Latn  1.0000    20937     997
118  swe_Latn  khk_Cyrl  1.0000    19940    1994
119  swe_Latn  urd_Arab  1.0000    19940    1994
120  swe_Latn  ben_Beng  1.0000    19940    1994

[121 rows x 5 columns]

In [6]:
df = pd.read_csv("results/eigen_other_eng.csv")
leave_two_out(df, output_dir="results/other_eng_lto", name="eigen_other_eng_lto", seed=42, lang_col="src_lang")

Leave-two-out: 121 combinations, lang_col='src_lang'
  SVO=fra  SOV=jpn : acc=0.7743
  SVO=fra  SOV=kor : acc=0.9724
  SVO=fra  SOV=tur : acc=0.7879
  SVO=fra  SOV=pes : acc=0.8831
  SVO=fra  SOV=hin : acc=0.9744
  SVO=fra  SOV=kat : acc=0.8706
  SVO=fra  SOV=tam : acc=0.9910
  SVO=fra  SOV=aze : acc=0.9860
  SVO=fra  SOV=khk : acc=0.9443
  SVO=fra  SOV=urd : acc=0.8721
  SVO=fra  SOV=ben : acc=0.9709
  SVO=deu  SOV=jpn : acc=0.7392
  SVO=deu  SOV=kor : acc=0.9358
  SVO=deu  SOV=tur : acc=0.7683
  SVO=deu  SOV=pes : acc=0.8506
  SVO=deu  SOV=hin : acc=0.9398
  SVO=deu  SOV=kat : acc=0.8410
  SVO=deu  SOV=tam : acc=0.9529
  SVO=deu  SOV=aze : acc=0.9117
  SVO=deu  SOV=khk : acc=0.9092
  SVO=deu  SOV=urd : acc=0.8350
  SVO=deu  SOV=ben : acc=0.9388
  SVO=tha  SOV=jpn : acc=0.4473
  SVO=tha  SOV=kor : acc=0.5692
  SVO=tha  SOV=tur : acc=0.3626
  SVO=tha  SOV=pes : acc=0.4885
  SVO=tha  SOV=hin : acc=0.5572
  SVO=tha  SOV=kat : acc=0.5271
  SVO=tha  SOV=tam : acc=0.5848
  SVO=tha  SOV=aze : acc=0.1725
  SVO=tha  SOV=khk : acc=0.5562
  SVO=tha  SOV=urd : acc=0.6068
  SVO=tha  SOV=ben : acc=0.5491
  SVO=ind  SOV=jpn : acc=0.7447
  SVO=ind  SOV=kor : acc=0.9273
  SVO=ind  SOV=tur : acc=0.7693
  SVO=ind  SOV=pes : acc=0.8526
  SVO=ind  SOV=hin : acc=0.9313
  SVO=ind  SOV=kat : acc=0.8144
  SVO=ind  SOV=tam : acc=0.9448
  SVO=ind  SOV=aze : acc=0.8957
  SVO=ind  SOV=khk : acc=0.9052
  SVO=ind  SOV=urd : acc=0.8290
  SVO=ind  SOV=ben : acc=0.9313
  SVO=zho  SOV=jpn : acc=0.5191
  SVO=zho  SOV=kor : acc=0.5476
  SVO=zho  SOV=tur : acc=0.3450
  SVO=zho  SOV=pes : acc=0.4764
  SVO=zho  SOV=hin : acc=0.5241
  SVO=zho  SOV=kat : acc=0.4413
  SVO=zho  SOV=tam : acc=0.5612
  SVO=zho  SOV=aze : acc=0.1254
  SVO=zho  SOV=khk : acc=0.5211
  SVO=zho  SOV=urd : acc=0.4975
  SVO=zho  SOV=ben : acc=0.5381
  SVO=rus  SOV=jpn : acc=0.6836
  SVO=rus  SOV=kor : acc=0.8636
  SVO=rus  SOV=tur : acc=0.7242
  SVO=rus  SOV=pes : acc=0.7884
  SVO=rus  SOV=hin : acc=0.8656
  SVO=rus  SOV=kat : acc=0.8019
  SVO=rus  SOV=tam : acc=0.8746
  SVO=rus  SOV=aze : acc=0.7623
  SVO=rus  SOV=khk : acc=0.8345
  SVO=rus  SOV=urd : acc=0.7477
  SVO=rus  SOV=ben : acc=0.8591
  SVO=vie  SOV=jpn : acc=0.6394
  SVO=vie  SOV=kor : acc=0.8711
  SVO=vie  SOV=tur : acc=0.7161
  SVO=vie  SOV=pes : acc=0.8250
  SVO=vie  SOV=hin : acc=0.8676
  SVO=vie  SOV=kat : acc=0.7828
  SVO=vie  SOV=tam : acc=0.8887
  SVO=vie  SOV=aze : acc=0.7813
  SVO=vie  SOV=khk : acc=0.8651
  SVO=vie  SOV=urd : acc=0.7768
  SVO=vie  SOV=ben : acc=0.8771
  SVO=por  SOV=jpn : acc=0.7678
  SVO=por  SOV=kor : acc=0.9684
  SVO=por  SOV=tur : acc=0.7889
  SVO=por  SOV=pes : acc=0.8771
  SVO=por  SOV=hin : acc=0.9729
  SVO=por  SOV=kat : acc=0.8736
  SVO=por  SOV=tam : acc=0.9885
  SVO=por  SOV=aze : acc=0.9860
  SVO=por  SOV=khk : acc=0.9423
  SVO=por  SOV=urd : acc=0.8751
  SVO=por  SOV=ben : acc=0.9694
  SVO=swh  SOV=jpn : acc=0.5787
  SVO=swh  SOV=kor : acc=0.8230
  SVO=swh  SOV=tur : acc=0.6063
  SVO=swh  SOV=pes : acc=0.7442
  SVO=swh  SOV=hin : acc=0.8320
  SVO=swh  SOV=kat : acc=0.6459
  SVO=swh  SOV=tam : acc=0.8320
  SVO=swh  SOV=aze : acc=0.6600
  SVO=swh  SOV=khk : acc=0.8064
  SVO=swh  SOV=urd : acc=0.7332
  SVO=swh  SOV=ben : acc=0.8285
  SVO=fin  SOV=jpn : acc=0.6936
  SVO=fin  SOV=kor : acc=0.8636
  SVO=fin  SOV=tur : acc=0.7538
  SVO=fin  SOV=pes : acc=0.7593
  SVO=fin  SOV=hin : acc=0.8666
  SVO=fin  SOV=kat : acc=0.7803
  SVO=fin  SOV=tam : acc=0.8761
  SVO=fin  SOV=aze : acc=0.7723
  SVO=fin  SOV=khk : acc=0.8586
  SVO=fin  SOV=urd : acc=0.7718
  SVO=fin  SOV=ben : acc=0.8576
  SVO=swe  SOV=jpn : acc=0.7643
  SVO=swe  SOV=kor : acc=0.9659
  SVO=swe  SOV=tur : acc=0.7879
  SVO=swe  SOV=pes : acc=0.8771
  SVO=swe  SOV=hin : acc=0.9739
  SVO=swe  SOV=kat : acc=0.8671
  SVO=swe  SOV=tam : acc=0.9875
  SVO=swe  SOV=aze : acc=0.9799
  SVO=swe  SOV=khk : acc=0.9398
  SVO=swe  SOV=urd : acc=0.8761
  SVO=swe  SOV=ben : acc=0.9669

Overall LTO: 0.7797 ± 0.1735
Saved LTO results to results/other_eng_lto/

     held_svo  held_sov     acc  n_train  n_test
0    fra_Latn  jpn_Jpan  0.7743    19940    1994
1    fra_Latn  kor_Hang  0.9724    19940    1994
2    fra_Latn  tur_Latn  0.7879    19940    1994
3    fra_Latn  pes_Arab  0.8831    19940    1994
4    fra_Latn  hin_Deva  0.9744    19940    1994
..        ...       ...     ...      ...     ...
116  swe_Latn  tam_Taml  0.9875    19940    1994
117  swe_Latn  aze_Latn  0.9799    20937     997
118  swe_Latn  khk_Cyrl  0.9398    19940    1994
119  swe_Latn  urd_Arab  0.8761    19940    1994
120  swe_Latn  ben_Beng  0.9669    19940    1994

[121 rows x 5 columns]

In [4]:
df = pd.read_csv("results/eigen_eng_other.csv")
leave_one_out(df, output_dir="results/eng_other_loo", name="eng_other_loo", seed=42, lang_col="tgt_lang")

Leave-one-out: 22 languages, lang_col='tgt_lang'
  fra    (SVO): acc=1.0000
  deu    (SVO): acc=1.0000
  tha    (SVO): acc=0.6419
  ind    (SVO): acc=1.0000
  zho    (SVO): acc=0.2728
  rus    (SVO): acc=0.9890
  vie    (SVO): acc=1.0000
  por    (SVO): acc=1.0000
  swh    (SVO): acc=0.8516
  fin    (SVO): acc=0.3651
  swe    (SVO): acc=1.0000
  jpn    (SOV): acc=0.9940
  kor    (SOV): acc=0.9990
  tur    (SOV): acc=1.0000
  pes    (SOV): acc=0.2006
  hin    (SOV): acc=1.0000
  kat    (SOV): acc=0.8245
  tam    (SOV): acc=1.0000
  azj    (SOV): acc=1.0000
  khk    (SOV): acc=1.0000
  urd    (SOV): acc=1.0000
  ben    (SOV): acc=1.0000

Overall LOO: 0.8699 ± 0.2505
Saved LOO results to results/eng_other_loo/

        lang word_order     acc  n_train  n_test
0   fra_Latn        SVO  1.0000    20937     997
1   deu_Latn        SVO  1.0000    20937     997
2   tha_Thai        SVO  0.6419    20937     997
3   ind_Latn        SVO  1.0000    20937     997
4   zho_Hans        SVO  0.2728    20937     997
5   rus_Cyrl        SVO  0.9890    20937     997
6   vie_Latn        SVO  1.0000    20937     997
7   por_Latn        SVO  1.0000    20937     997
8   swh_Latn        SVO  0.8516    20937     997
9   fin_Latn        SVO  0.3651    20937     997
10  swe_Latn        SVO  1.0000    20937     997
11  jpn_Jpan        SOV  0.9940    20937     997
12  kor_Hang        SOV  0.9990    20937     997
13  tur_Latn        SOV  1.0000    20937     997
14  pes_Arab        SOV  0.2006    20937     997
15  hin_Deva        SOV  1.0000    20937     997
16  kat_Geor        SOV  0.8245    20937     997
17  tam_Taml        SOV  1.0000    20937     997
18  azj_Latn        SOV  1.0000    20937     997
19  khk_Cyrl        SOV  1.0000    20937     997
20  urd_Arab        SOV  1.0000    20937     997
21  ben_Beng        SOV  1.0000    20937     997

In [5]:
df = pd.read_csv("results/eigen_other_eng.csv")
leave_one_out(df, output_dir="results/other_eng_loo", name="other_eng_loo", seed=42, lang_col="src_lang")

Leave-one-out: 22 languages, lang_col='src_lang'
  fra    (SVO): acc=0.9860
  deu    (SVO): acc=0.9117
  tha    (SVO): acc=0.1725
  ind    (SVO): acc=0.8957
  zho    (SVO): acc=0.1254
  rus    (SVO): acc=0.7623
  vie    (SVO): acc=0.7813
  por    (SVO): acc=0.9860
  swh    (SVO): acc=0.6600
  fin    (SVO): acc=0.7723
  swe    (SVO): acc=0.9799
  jpn    (SOV): acc=0.5527
  kor    (SOV): acc=0.9549
  tur    (SOV): acc=0.5817
  pes    (SOV): acc=0.7753
  hin    (SOV): acc=0.9569
  kat    (SOV): acc=0.7503
  tam    (SOV): acc=0.9920
  azj    (SOV): acc=0.9338
  khk    (SOV): acc=0.9027
  urd    (SOV): acc=0.7623
  ben    (SOV): acc=0.9509

Overall LOO: 0.7794 ± 0.2369
Saved LOO results to results/other_eng_loo/

        lang word_order     acc  n_train  n_test
0   fra_Latn        SVO  0.9860    20937     997
1   deu_Latn        SVO  0.9117    20937     997
2   tha_Thai        SVO  0.1725    20937     997
3   ind_Latn        SVO  0.8957    20937     997
4   zho_Hans        SVO  0.1254    20937     997
5   rus_Cyrl        SVO  0.7623    20937     997
6   vie_Latn        SVO  0.7813    20937     997
7   por_Latn        SVO  0.9860    20937     997
8   swh_Latn        SVO  0.6600    20937     997
9   fin_Latn        SVO  0.7723    20937     997
10  swe_Latn        SVO  0.9799    20937     997
11  jpn_Jpan        SOV  0.5527    20937     997
12  kor_Hang        SOV  0.9549    20937     997
13  tur_Latn        SOV  0.5817    20937     997
14  pes_Arab        SOV  0.7753    20937     997
15  hin_Deva        SOV  0.9569    20937     997
16  kat_Geor        SOV  0.7503    20937     997
17  tam_Taml        SOV  0.9920    20937     997
18  azj_Latn        SOV  0.9338    20937     997
19  khk_Cyrl        SOV  0.9027    20937     997
20  urd_Arab        SOV  0.7623    20937     997
21  ben_Beng        SOV  0.9509    20937     997