## Eigenvalues probing

In [21]:
# !pip install ipywidgets

In [1]:
from build_dataset import build_dataset
from analyze import run_analysis
from analyze import leave_one_out
import os
import pandas as pd

---
## Model: nllb-200-3.3B

### Create datasets

In [23]:
os.makedirs("results/3.3B", exist_ok=True)

In [24]:
build_dataset(attn_root="outputs/nllb-200-3.3B/attentions/", output_csv="results/3.3B/eigen_eng_other.csv", mode=1, topk=12, limit_per_pair=None, overwrite=False)

Dataset already exists at results/3.3B/eigen_eng_other.csv. Use --overwrite to rebuild.

In [25]:
build_dataset(attn_root="outputs/nllb-200-3.3B/attentions/", output_csv="results/3.3B/eigen_other_eng.csv", mode=2, topk=12, limit_per_pair=None, overwrite=False)

Dataset already exists at results/3.3B/eigen_other_eng.csv. Use --overwrite to rebuild.

### Run analysis

In [26]:
df = pd.read_csv("results/3.3B/eigen_eng_other.csv")
run_analysis(df, output_dir="results/3.3B/eng_other", n_splits=5, seeds=[42, 1, 2], name="3.3B_eng_other")

Detected: 24 layers × 16 heads
Dataset: 21934 samples, class balance: [10967 10967]

[1/4] Full features
  acc = 0.9998 ± 0.0002

[2/4] Per-layer
  L00: 0.8827 ± 0.0059
  L01: 0.8570 ± 0.0071
  L02: 0.9119 ± 0.0037
  L03: 0.9488 ± 0.0025
  L04: 0.9586 ± 0.0038
  L05: 0.9544 ± 0.0039
  L06: 0.9386 ± 0.0042
  L07: 0.9533 ± 0.0028
  L08: 0.9458 ± 0.0036
  L09: 0.9584 ± 0.0025
  L10: 0.9633 ± 0.0022
  L11: 0.9779 ± 0.0025
  L12: 0.9299 ± 0.0024
  L13: 0.9346 ± 0.0028
  L14: 0.8755 ± 0.0040
  L15: 0.9274 ± 0.0032
  L16: 0.9239 ± 0.0042
  L17: 0.8544 ± 0.0053
  L18: 0.8292 ± 0.0048
  L19: 0.8317 ± 0.0067
  L20: 0.8596 ± 0.0049
  L21: 0.8207 ± 0.0060
  L22: 0.7940 ± 0.0074
  L23: 0.8287 ± 0.0040

[3/4] Per-head
  H00: 0.9408 ± 0.0036
  H01: 0.9550 ± 0.0036
  H02: 0.9697 ± 0.0019
  H03: 0.9882 ± 0.0019
  H04: 0.9527 ± 0.0034
  H05: 0.9531 ± 0.0024
  H06: 0.9638 ± 0.0024
  H07: 0.9454 ± 0.0033
  H08: 0.9567 ± 0.0028
  H09: 0.9678 ± 0.0026
  H10: 0.9551 ± 0.0025
  H11: 0.9291 ± 0.0046
  H12: 0.9786 ± 0.0023
  H13: 0.9128 ± 0.0045
  H14: 0.9099 ± 0.0044
  H15: 0.9553 ± 0.0029

[4/4] Heatmap (24×16 = 384 probes)
  Layer 00 done
  Layer 01 done
  Layer 02 done
  Layer 03 done
  Layer 04 done
  Layer 05 done
  Layer 06 done
  Layer 07 done
  Layer 08 done
  Layer 09 done
  Layer 10 done
  Layer 11 done
  Layer 12 done
  Layer 13 done
  Layer 14 done
  Layer 15 done
  Layer 16 done
  Layer 17 done
  Layer 18 done
  Layer 19 done
  Layer 20 done
  Layer 21 done
  Layer 22 done
  Layer 23 done

All outputs saved to results/3.3B/eng_other/

In [27]:
df = pd.read_csv("results/3.3B/eigen_other_eng.csv")
run_analysis(df, output_dir="results/3.3B/other_eng", n_splits=5, seeds=[42, 1, 2], name="3.3B_other_eng")

Detected: 24 layers × 16 heads
Dataset: 21934 samples, class balance: [10967 10967]

[1/4] Full features
  acc = 0.9187 ± 0.0053

[2/4] Per-layer
  L00: 0.7188 ± 0.0057
  L01: 0.7230 ± 0.0051
  L02: 0.6737 ± 0.0047
  L03: 0.7095 ± 0.0065
  L04: 0.7318 ± 0.0063
  L05: 0.7428 ± 0.0077
  L06: 0.6944 ± 0.0065
  L07: 0.6664 ± 0.0056
  L08: 0.6923 ± 0.0073
  L09: 0.6475 ± 0.0054
  L10: 0.6395 ± 0.0090
  L11: 0.6577 ± 0.0055
  L12: 0.6369 ± 0.0093
  L13: 0.6323 ± 0.0089
  L14: 0.6672 ± 0.0054
  L15: 0.6345 ± 0.0078
  L16: 0.6410 ± 0.0059
  L17: 0.6222 ± 0.0081
  L18: 0.6866 ± 0.0066
  L19: 0.6294 ± 0.0067
  L20: 0.6356 ± 0.0084
  L21: 0.6159 ± 0.0069
  L22: 0.6638 ± 0.0071
  L23: 0.6590 ± 0.0075

[3/4] Per-head
  H00: 0.6985 ± 0.0076
  H01: 0.6993 ± 0.0062
  H02: 0.6994 ± 0.0045
  H03: 0.7063 ± 0.0046
  H04: 0.7495 ± 0.0048
  H05: 0.7245 ± 0.0064
  H06: 0.6831 ± 0.0075
  H07: 0.7527 ± 0.0061
  H08: 0.7126 ± 0.0063
  H09: 0.6662 ± 0.0047
  H10: 0.6921 ± 0.0071
  H11: 0.7230 ± 0.0056
  H12: 0.7600 ± 0.0047
  H13: 0.7092 ± 0.0046
  H14: 0.6944 ± 0.0067
  H15: 0.7063 ± 0.0067

[4/4] Heatmap (24×16 = 384 probes)
  Layer 00 done
  Layer 01 done
  Layer 02 done
  Layer 03 done
  Layer 04 done
  Layer 05 done
  Layer 06 done
  Layer 07 done
  Layer 08 done
  Layer 09 done
  Layer 10 done
  Layer 11 done
  Layer 12 done
  Layer 13 done
  Layer 14 done
  Layer 15 done
  Layer 16 done
  Layer 17 done
  Layer 18 done
  Layer 19 done
  Layer 20 done
  Layer 21 done
  Layer 22 done
  Layer 23 done

All outputs saved to results/3.3B/other_eng/

### Leave-one-out

In [2]:
df = pd.read_csv("results/3.3B/eigen_eng_other.csv")
leave_one_out(df, output_dir="results/3.3B/eng_other_loo", name="3.3B_eng_other_loo", seed=42, lang_col="tgt_lang")

Leave-one-out: 22 languages, lang_col='tgt_lang'
  fra    (SVO): acc=1.0000
  deu    (SVO): acc=1.0000
  tha    (SVO): acc=0.6419
  ind    (SVO): acc=1.0000
  zho    (SVO): acc=0.2728
  rus    (SVO): acc=0.9890
  vie    (SVO): acc=1.0000
  por    (SVO): acc=1.0000
  swh    (SVO): acc=0.8516
  fin    (SVO): acc=0.3651
  swe    (SVO): acc=1.0000
  jpn    (SOV): acc=0.9940
  kor    (SOV): acc=0.9990
  tur    (SOV): acc=1.0000
  pes    (SOV): acc=0.2006
  hin    (SOV): acc=1.0000
  kat    (SOV): acc=0.8245
  tam    (SOV): acc=1.0000
  azj    (SOV): acc=1.0000
  khk    (SOV): acc=1.0000
  urd    (SOV): acc=1.0000
  ben    (SOV): acc=1.0000

Overall LOO: 0.8699 ± 0.2505
Saved LOO results to results/3.3B/eng_other_loo/

        lang word_order     acc  n_train  n_test
0   fra_Latn        SVO  1.0000    20937     997
1   deu_Latn        SVO  1.0000    20937     997
2   tha_Thai        SVO  0.6419    20937     997
3   ind_Latn        SVO  1.0000    20937     997
4   zho_Hans        SVO  0.2728    20937     997
5   rus_Cyrl        SVO  0.9890    20937     997
6   vie_Latn        SVO  1.0000    20937     997
7   por_Latn        SVO  1.0000    20937     997
8   swh_Latn        SVO  0.8516    20937     997
9   fin_Latn        SVO  0.3651    20937     997
10  swe_Latn        SVO  1.0000    20937     997
11  jpn_Jpan        SOV  0.9940    20937     997
12  kor_Hang        SOV  0.9990    20937     997
13  tur_Latn        SOV  1.0000    20937     997
14  pes_Arab        SOV  0.2006    20937     997
15  hin_Deva        SOV  1.0000    20937     997
16  kat_Geor        SOV  0.8245    20937     997
17  tam_Taml        SOV  1.0000    20937     997
18  azj_Latn        SOV  1.0000    20937     997
19  khk_Cyrl        SOV  1.0000    20937     997
20  urd_Arab        SOV  1.0000    20937     997
21  ben_Beng        SOV  1.0000    20937     997

In [3]:
df = pd.read_csv("results/3.3B/eigen_other_eng.csv")
leave_one_out(df, output_dir="results/3.3B/other_eng_loo", name="3.3B_other_eng_loo", seed=42, lang_col="src_lang")

Leave-one-out: 22 languages, lang_col='src_lang'
  fra    (SVO): acc=0.9860
  deu    (SVO): acc=0.9117
  tha    (SVO): acc=0.1725
  ind    (SVO): acc=0.8957
  zho    (SVO): acc=0.1254
  rus    (SVO): acc=0.7623
  vie    (SVO): acc=0.7813
  por    (SVO): acc=0.9860
  swh    (SVO): acc=0.6600
  fin    (SVO): acc=0.7723
  swe    (SVO): acc=0.9799
  jpn    (SOV): acc=0.5527
  kor    (SOV): acc=0.9549
  tur    (SOV): acc=0.5817
  pes    (SOV): acc=0.7753
  hin    (SOV): acc=0.9569
  kat    (SOV): acc=0.7503
  tam    (SOV): acc=0.9920
  azj    (SOV): acc=0.9338
  khk    (SOV): acc=0.9027
  urd    (SOV): acc=0.7623
  ben    (SOV): acc=0.9509

Overall LOO: 0.7794 ± 0.2369
Saved LOO results to results/3.3B/other_eng_loo/

        lang word_order     acc  n_train  n_test
0   fra_Latn        SVO  0.9860    20937     997
1   deu_Latn        SVO  0.9117    20937     997
2   tha_Thai        SVO  0.1725    20937     997
3   ind_Latn        SVO  0.8957    20937     997
4   zho_Hans        SVO  0.1254    20937     997
5   rus_Cyrl        SVO  0.7623    20937     997
6   vie_Latn        SVO  0.7813    20937     997
7   por_Latn        SVO  0.9860    20937     997
8   swh_Latn        SVO  0.6600    20937     997
9   fin_Latn        SVO  0.7723    20937     997
10  swe_Latn        SVO  0.9799    20937     997
11  jpn_Jpan        SOV  0.5527    20937     997
12  kor_Hang        SOV  0.9549    20937     997
13  tur_Latn        SOV  0.5817    20937     997
14  pes_Arab        SOV  0.7753    20937     997
15  hin_Deva        SOV  0.9569    20937     997
16  kat_Geor        SOV  0.7503    20937     997
17  tam_Taml        SOV  0.9920    20937     997
18  azj_Latn        SOV  0.9338    20937     997
19  khk_Cyrl        SOV  0.9027    20937     997
20  urd_Arab        SOV  0.7623    20937     997
21  ben_Beng        SOV  0.9509    20937     997

---
## Model: nllb-200-distilled-1.3B

### Create datasets

In [30]:
os.makedirs("results/1.3B", exist_ok=True)

In [31]:
build_dataset(attn_root="outputs/nllb-200-distilled-1.3B/attentions/", output_csv="results/1.3B/eigen_eng_other.csv", mode=1, topk=12, limit_per_pair=None, overwrite=False)

Dataset already exists at results/1.3B/eigen_eng_other.csv. Use --overwrite to rebuild.

In [32]:
build_dataset(attn_root="outputs/nllb-200-distilled-1.3B/attentions/", output_csv="results/1.3B/eigen_other_eng.csv", mode=2, topk=12, limit_per_pair=None, overwrite=False)

Dataset already exists at results/1.3B/eigen_other_eng.csv. Use --overwrite to rebuild.

### Run analysis

In [33]:
df = pd.read_csv("results/1.3B/eigen_eng_other.csv")
run_analysis(df, output_dir="results/1.3B/eng_other", n_splits=5, seeds=[42, 1, 2], name="1.3B_eng_other")

Detected: 24 layers × 16 heads
Dataset: 21934 samples, class balance: [10967 10967]

[1/4] Full features
  acc = 0.9998 ± 0.0004

[2/4] Per-layer
  L00: 0.9245 ± 0.0051
  L01: 0.8620 ± 0.0068
  L02: 0.8810 ± 0.0049
  L03: 0.9291 ± 0.0030
  L04: 0.9595 ± 0.0034
  L05: 0.9492 ± 0.0030
  L06: 0.9418 ± 0.0028
  L07: 0.9653 ± 0.0032
  L08: 0.9348 ± 0.0026
  L09: 0.9548 ± 0.0028
  L10: 0.9716 ± 0.0022
  L11: 0.9722 ± 0.0019
  L12: 0.9718 ± 0.0020
  L13: 0.9816 ± 0.0019
  L14: 0.9308 ± 0.0042
  L15: 0.9377 ± 0.0027
  L16: 0.9111 ± 0.0036
  L17: 0.8985 ± 0.0026
  L18: 0.9088 ± 0.0068
  L19: 0.8500 ± 0.0040
  L20: 0.7876 ± 0.0060
  L21: 0.8701 ± 0.0040
  L22: 0.8577 ± 0.0050
  L23: 0.8152 ± 0.0067

[3/4] Per-head
  H00: 0.9789 ± 0.0022
  H01: 0.9727 ± 0.0032
  H02: 0.9440 ± 0.0029
  H03: 0.9317 ± 0.0030
  H04: 0.9411 ± 0.0026
  H05: 0.9650 ± 0.0027
  H06: 0.9542 ± 0.0033
  H07: 0.9668 ± 0.0022
  H08: 0.9682 ± 0.0022
  H09: 0.9721 ± 0.0028
  H10: 0.9650 ± 0.0031
  H11: 0.9708 ± 0.0027
  H12: 0.9722 ± 0.0028
  H13: 0.9636 ± 0.0022
  H14: 0.9730 ± 0.0030
  H15: 0.9725 ± 0.0026

[4/4] Heatmap (24×16 = 384 probes)
  Layer 00 done
  Layer 01 done
  Layer 02 done
  Layer 03 done
  Layer 04 done
  Layer 05 done
  Layer 06 done
  Layer 07 done
  Layer 08 done
  Layer 09 done
  Layer 10 done
  Layer 11 done
  Layer 12 done
  Layer 13 done
  Layer 14 done
  Layer 15 done
  Layer 16 done
  Layer 17 done
  Layer 18 done
  Layer 19 done
  Layer 20 done
  Layer 21 done
  Layer 22 done
  Layer 23 done

All outputs saved to results/1.3B/eng_other/

In [34]:
df = pd.read_csv("results/1.3B/eigen_other_eng.csv")
run_analysis(df, output_dir="results/1.3B/other_eng", n_splits=5, seeds=[42, 1, 2], name="1.3B_other_eng")

Detected: 24 layers × 16 heads
Dataset: 21934 samples, class balance: [10967 10967]

[1/4] Full features
  acc = 0.9057 ± 0.0043

[2/4] Per-layer
  L00: 0.6976 ± 0.0068
  L01: 0.7098 ± 0.0038
  L02: 0.6431 ± 0.0068
  L03: 0.7214 ± 0.0058
  L04: 0.7085 ± 0.0060
  L05: 0.6742 ± 0.0066
  L06: 0.6803 ± 0.0054
  L07: 0.6899 ± 0.0077
  L08: 0.7164 ± 0.0081
  L09: 0.6506 ± 0.0061
  L10: 0.6930 ± 0.0078
  L11: 0.7098 ± 0.0072
  L12: 0.6613 ± 0.0076
  L13: 0.6527 ± 0.0077
  L14: 0.6488 ± 0.0072
  L15: 0.6475 ± 0.0067
  L16: 0.6476 ± 0.0071
  L17: 0.6220 ± 0.0053
  L18: 0.6327 ± 0.0048
  L19: 0.6581 ± 0.0064
  L20: 0.6185 ± 0.0061
  L21: 0.6377 ± 0.0067
  L22: 0.6738 ± 0.0089
  L23: 0.7045 ± 0.0067

[3/4] Per-head
  H00: 0.7033 ± 0.0108
  H01: 0.6794 ± 0.0055
  H02: 0.7513 ± 0.0077
  H03: 0.6818 ± 0.0051
  H04: 0.6905 ± 0.0044
  H05: 0.7079 ± 0.0060
  H06: 0.7324 ± 0.0080
  H07: 0.7234 ± 0.0061
  H08: 0.6972 ± 0.0057
  H09: 0.6719 ± 0.0089
  H10: 0.7343 ± 0.0072
  H11: 0.7300 ± 0.0058
  H12: 0.7239 ± 0.0062
  H13: 0.7077 ± 0.0058
  H14: 0.7104 ± 0.0098
  H15: 0.7052 ± 0.0074

[4/4] Heatmap (24×16 = 384 probes)
  Layer 00 done
  Layer 01 done
  Layer 02 done
  Layer 03 done
  Layer 04 done
  Layer 05 done
  Layer 06 done
  Layer 07 done
  Layer 08 done
  Layer 09 done
  Layer 10 done
  Layer 11 done
  Layer 12 done
  Layer 13 done
  Layer 14 done
  Layer 15 done
  Layer 16 done
  Layer 17 done
  Layer 18 done
  Layer 19 done
  Layer 20 done
  Layer 21 done
  Layer 22 done
  Layer 23 done

All outputs saved to results/1.3B/other_eng/

### Leave-one-out

In [4]:
df = pd.read_csv("results/1.3B/eigen_eng_other.csv")
leave_one_out(df, output_dir="results/1.3B/eng_other_loo", name="1.3B_eng_other_loo", seed=42, lang_col="tgt_lang")

Leave-one-out: 22 languages, lang_col='tgt_lang'
  fra    (SVO): acc=1.0000
  deu    (SVO): acc=0.9990
  tha    (SVO): acc=0.8185
  ind    (SVO): acc=1.0000
  zho    (SVO): acc=0.4945
  rus    (SVO): acc=1.0000
  vie    (SVO): acc=1.0000
  por    (SVO): acc=1.0000
  swh    (SVO): acc=0.9980
  fin    (SVO): acc=0.4664
  swe    (SVO): acc=1.0000
  jpn    (SOV): acc=0.9930
  kor    (SOV): acc=1.0000
  tur    (SOV): acc=1.0000
  pes    (SOV): acc=0.3310
  hin    (SOV): acc=1.0000
  kat    (SOV): acc=0.7402
  tam    (SOV): acc=1.0000
  azj    (SOV): acc=1.0000
  khk    (SOV): acc=0.9980
  urd    (SOV): acc=1.0000
  ben    (SOV): acc=1.0000

Overall LOO: 0.9018 ± 0.1995
Saved LOO results to results/1.3B/eng_other_loo/

        lang word_order     acc  n_train  n_test
0   fra_Latn        SVO  1.0000    20937     997
1   deu_Latn        SVO  0.9990    20937     997
2   tha_Thai        SVO  0.8185    20937     997
3   ind_Latn        SVO  1.0000    20937     997
4   zho_Hans        SVO  0.4945    20937     997
5   rus_Cyrl        SVO  1.0000    20937     997
6   vie_Latn        SVO  1.0000    20937     997
7   por_Latn        SVO  1.0000    20937     997
8   swh_Latn        SVO  0.9980    20937     997
9   fin_Latn        SVO  0.4664    20937     997
10  swe_Latn        SVO  1.0000    20937     997
11  jpn_Jpan        SOV  0.9930    20937     997
12  kor_Hang        SOV  1.0000    20937     997
13  tur_Latn        SOV  1.0000    20937     997
14  pes_Arab        SOV  0.3310    20937     997
15  hin_Deva        SOV  1.0000    20937     997
16  kat_Geor        SOV  0.7402    20937     997
17  tam_Taml        SOV  1.0000    20937     997
18  azj_Latn        SOV  1.0000    20937     997
19  khk_Cyrl        SOV  0.9980    20937     997
20  urd_Arab        SOV  1.0000    20937     997
21  ben_Beng        SOV  1.0000    20937     997

In [5]:
df = pd.read_csv("results/1.3B/eigen_other_eng.csv")
leave_one_out(df, output_dir="results/1.3B/other_eng_loo", name="1.3B_other_eng_loo", seed=42, lang_col="src_lang")

Leave-one-out: 22 languages, lang_col='src_lang'
  fra    (SVO): acc=0.9789
  deu    (SVO): acc=0.9137
  tha    (SVO): acc=0.1545
  ind    (SVO): acc=0.8345
  zho    (SVO): acc=0.0702
  rus    (SVO): acc=0.5637
  vie    (SVO): acc=0.7462
  por    (SVO): acc=0.9599
  swh    (SVO): acc=0.8044
  fin    (SVO): acc=0.7854
  swe    (SVO): acc=0.9689
  jpn    (SOV): acc=0.5496
  kor    (SOV): acc=0.9288
  tur    (SOV): acc=0.4413
  pes    (SOV): acc=0.7763
  hin    (SOV): acc=0.9258
  kat    (SOV): acc=0.7031
  tam    (SOV): acc=0.9910
  azj    (SOV): acc=0.9418
  khk    (SOV): acc=0.9408
  urd    (SOV): acc=0.8405
  ben    (SOV): acc=0.9117

Overall LOO: 0.7605 ± 0.2521
Saved LOO results to results/1.3B/other_eng_loo/

        lang word_order     acc  n_train  n_test
0   fra_Latn        SVO  0.9789    20937     997
1   deu_Latn        SVO  0.9137    20937     997
2   tha_Thai        SVO  0.1545    20937     997
3   ind_Latn        SVO  0.8345    20937     997
4   zho_Hans        SVO  0.0702    20937     997
5   rus_Cyrl        SVO  0.5637    20937     997
6   vie_Latn        SVO  0.7462    20937     997
7   por_Latn        SVO  0.9599    20937     997
8   swh_Latn        SVO  0.8044    20937     997
9   fin_Latn        SVO  0.7854    20937     997
10  swe_Latn        SVO  0.9689    20937     997
11  jpn_Jpan        SOV  0.5496    20937     997
12  kor_Hang        SOV  0.9288    20937     997
13  tur_Latn        SOV  0.4413    20937     997
14  pes_Arab        SOV  0.7763    20937     997
15  hin_Deva        SOV  0.9258    20937     997
16  kat_Geor        SOV  0.7031    20937     997
17  tam_Taml        SOV  0.9910    20937     997
18  azj_Latn        SOV  0.9418    20937     997
19  khk_Cyrl        SOV  0.9408    20937     997
20  urd_Arab        SOV  0.8405    20937     997
21  ben_Beng        SOV  0.9117    20937     997

---
## Model: nllb-200-distilled-600M

### Create datasets

In [37]:
os.makedirs("results/600M", exist_ok=True)

In [38]:
build_dataset(attn_root="outputs/nllb-200-distilled-600M/attentions/", output_csv="results/600M/eigen_eng_other.csv", mode=1, topk=12, limit_per_pair=None, overwrite=False)

Found 21934 attention files across 22 pairs.

Extracting eigenvalues:   0%|          | 1/21934 [00:00<55:49,  6.55it/s]

Detected: 12 layers, 16 heads, topk=12

Extracting eigenvalues: 100%|██████████| 21934/21934 [09:29<00:00, 38.50it/s]

Saved 21934 rows → results/600M/eigen_eng_other.csv

In [39]:
build_dataset(attn_root="outputs/nllb-200-distilled-600M/attentions/", output_csv="results/600M/eigen_other_eng.csv", mode=2, topk=12, limit_per_pair=None, overwrite=False)

Found 21934 attention files across 22 pairs.

Extracting eigenvalues:   0%|          | 3/21934 [00:00<15:11, 24.06it/s]

Detected: 12 layers, 16 heads, topk=12

Extracting eigenvalues: 100%|██████████| 21934/21934 [08:22<00:00, 43.64it/s]

Saved 21934 rows → results/600M/eigen_other_eng.csv

### Run analysis

In [40]:
df = pd.read_csv("results/600M/eigen_eng_other.csv")
run_analysis(df, output_dir="results/600M/eng_other", n_splits=5, seeds=[42, 1, 2], name="600M_eng_other")

Detected: 12 layers × 16 heads
Dataset: 21934 samples, class balance: [10967 10967]

[1/4] Full features
  acc = 0.9992 ± 0.0005

[2/4] Per-layer
  L00: 0.9041 ± 0.0050
  L01: 0.8751 ± 0.0049
  L02: 0.9452 ± 0.0020
  L03: 0.9582 ± 0.0044
  L04: 0.9542 ± 0.0034
  L05: 0.9366 ± 0.0030
  L06: 0.9566 ± 0.0023
  L07: 0.9480 ± 0.0031
  L08: 0.9651 ± 0.0037
  L09: 0.8887 ± 0.0062
  L10: 0.8530 ± 0.0061
  L11: 0.8664 ± 0.0047

[3/4] Per-head
  H00: 0.9271 ± 0.0028
  H01: 0.8711 ± 0.0077
  H02: 0.8959 ± 0.0048
  H03: 0.9375 ± 0.0037
  H04: 0.8988 ± 0.0059
  H05: 0.9258 ± 0.0045
  H06: 0.9206 ± 0.0046
  H07: 0.9198 ± 0.0045
  H08: 0.9259 ± 0.0035
  H09: 0.9532 ± 0.0040
  H10: 0.9049 ± 0.0035
  H11: 0.9323 ± 0.0035
  H12: 0.8724 ± 0.0047
  H13: 0.9132 ± 0.0034
  H14: 0.9332 ± 0.0031
  H15: 0.9475 ± 0.0026

[4/4] Heatmap (12×16 = 192 probes)
  Layer 00 done
  Layer 01 done
  Layer 02 done
  Layer 03 done
  Layer 04 done
  Layer 05 done
  Layer 06 done
  Layer 07 done
  Layer 08 done
  Layer 09 done
  Layer 10 done
  Layer 11 done

All outputs saved to results/600M/eng_other/

In [41]:
df = pd.read_csv("results/600M/eigen_other_eng.csv")
run_analysis(df, output_dir="results/600M/other_eng", n_splits=5, seeds=[42, 1, 2], name="600M_other_eng")

Detected: 12 layers × 16 heads
Dataset: 21934 samples, class balance: [10967 10967]

[1/4] Full features
  acc = 0.9042 ± 0.0048

[2/4] Per-layer
  L00: 0.7605 ± 0.0074
  L01: 0.7282 ± 0.0058
  L02: 0.7422 ± 0.0060
  L03: 0.7356 ± 0.0069
  L04: 0.7089 ± 0.0053
  L05: 0.6903 ± 0.0046
  L06: 0.6962 ± 0.0054
  L07: 0.6908 ± 0.0091
  L08: 0.6292 ± 0.0069
  L09: 0.6303 ± 0.0064
  L10: 0.6497 ± 0.0071
  L11: 0.7854 ± 0.0063

[3/4] Per-head
  H00: 0.7196 ± 0.0067
  H01: 0.6643 ± 0.0090
  H02: 0.7133 ± 0.0058
  H03: 0.7350 ± 0.0056
  H04: 0.6455 ± 0.0069
  H05: 0.6406 ± 0.0058
  H06: 0.7116 ± 0.0060
  H07: 0.6365 ± 0.0042
  H08: 0.7337 ± 0.0073
  H09: 0.7446 ± 0.0051
  H10: 0.7266 ± 0.0079
  H11: 0.6529 ± 0.0085
  H12: 0.7079 ± 0.0059
  H13: 0.7005 ± 0.0057
  H14: 0.6916 ± 0.0082
  H15: 0.6124 ± 0.0046

[4/4] Heatmap (12×16 = 192 probes)
  Layer 00 done
  Layer 01 done
  Layer 02 done
  Layer 03 done
  Layer 04 done
  Layer 05 done
  Layer 06 done
  Layer 07 done
  Layer 08 done
  Layer 09 done
  Layer 10 done
  Layer 11 done

All outputs saved to results/600M/other_eng/

### Leave-one-out

In [6]:
df = pd.read_csv("results/600M/eigen_eng_other.csv")
leave_one_out(df, output_dir="results/600M/eng_other_loo", name="600M_eng_other_loo", seed=42, lang_col="tgt_lang")

Leave-one-out: 22 languages, lang_col='tgt_lang'
  fra    (SVO): acc=1.0000
  deu    (SVO): acc=0.9990
  tha    (SVO): acc=0.1274
  ind    (SVO): acc=0.9970
  zho    (SVO): acc=0.7362
  rus    (SVO): acc=0.9910
  vie    (SVO): acc=1.0000
  por    (SVO): acc=1.0000
  swh    (SVO): acc=1.0000
  fin    (SVO): acc=0.2166
  swe    (SVO): acc=1.0000
  jpn    (SOV): acc=0.9950
  kor    (SOV): acc=0.9990
  tur    (SOV): acc=1.0000
  pes    (SOV): acc=0.1966
  hin    (SOV): acc=1.0000
  kat    (SOV): acc=0.5998
  tam    (SOV): acc=1.0000
  azj    (SOV): acc=0.9990
  khk    (SOV): acc=0.9890
  urd    (SOV): acc=0.9990
  ben    (SOV): acc=1.0000

Overall LOO: 0.8566 ± 0.2859
Saved LOO results to results/600M/eng_other_loo/

        lang word_order     acc  n_train  n_test
0   fra_Latn        SVO  1.0000    20937     997
1   deu_Latn        SVO  0.9990    20937     997
2   tha_Thai        SVO  0.1274    20937     997
3   ind_Latn        SVO  0.9970    20937     997
4   zho_Hans        SVO  0.7362    20937     997
5   rus_Cyrl        SVO  0.9910    20937     997
6   vie_Latn        SVO  1.0000    20937     997
7   por_Latn        SVO  1.0000    20937     997
8   swh_Latn        SVO  1.0000    20937     997
9   fin_Latn        SVO  0.2166    20937     997
10  swe_Latn        SVO  1.0000    20937     997
11  jpn_Jpan        SOV  0.9950    20937     997
12  kor_Hang        SOV  0.9990    20937     997
13  tur_Latn        SOV  1.0000    20937     997
14  pes_Arab        SOV  0.1966    20937     997
15  hin_Deva        SOV  1.0000    20937     997
16  kat_Geor        SOV  0.5998    20937     997
17  tam_Taml        SOV  1.0000    20937     997
18  azj_Latn        SOV  0.9990    20937     997
19  khk_Cyrl        SOV  0.9890    20937     997
20  urd_Arab        SOV  0.9990    20937     997
21  ben_Beng        SOV  1.0000    20937     997

In [7]:
df = pd.read_csv("results/600M/eigen_other_eng.csv")
leave_one_out(df, output_dir="results/600M/other_eng_loo", name="600M_other_eng_loo", seed=42, lang_col="src_lang")

Leave-one-out: 22 languages, lang_col='src_lang'
  fra    (SVO): acc=0.9438
  deu    (SVO): acc=0.9318
  tha    (SVO): acc=0.1946
  ind    (SVO): acc=0.9117
  zho    (SVO): acc=0.0632
  rus    (SVO): acc=0.6229
  vie    (SVO): acc=0.7503
  por    (SVO): acc=0.9699
  swh    (SVO): acc=0.5667
  fin    (SVO): acc=0.8445
  swe    (SVO): acc=0.9829
  jpn    (SOV): acc=0.4433
  kor    (SOV): acc=0.9388
  tur    (SOV): acc=0.5045
  pes    (SOV): acc=0.8325
  hin    (SOV): acc=0.9037
  kat    (SOV): acc=0.8175
  tam    (SOV): acc=0.9378
  azj    (SOV): acc=0.9388
  khk    (SOV): acc=0.9438
  urd    (SOV): acc=0.8606
  ben    (SOV): acc=0.8435

Overall LOO: 0.7612 ± 0.2513
Saved LOO results to results/600M/other_eng_loo/

        lang word_order     acc  n_train  n_test
0   fra_Latn        SVO  0.9438    20937     997
1   deu_Latn        SVO  0.9318    20937     997
2   tha_Thai        SVO  0.1946    20937     997
3   ind_Latn        SVO  0.9117    20937     997
4   zho_Hans        SVO  0.0632    20937     997
5   rus_Cyrl        SVO  0.6229    20937     997
6   vie_Latn        SVO  0.7503    20937     997
7   por_Latn        SVO  0.9699    20937     997
8   swh_Latn        SVO  0.5667    20937     997
9   fin_Latn        SVO  0.8445    20937     997
10  swe_Latn        SVO  0.9829    20937     997
11  jpn_Jpan        SOV  0.4433    20937     997
12  kor_Hang        SOV  0.9388    20937     997
13  tur_Latn        SOV  0.5045    20937     997
14  pes_Arab        SOV  0.8325    20937     997
15  hin_Deva        SOV  0.9037    20937     997
16  kat_Geor        SOV  0.8175    20937     997
17  tam_Taml        SOV  0.9378    20937     997
18  azj_Latn        SOV  0.9388    20937     997
19  khk_Cyrl        SOV  0.9438    20937     997
20  urd_Arab        SOV  0.8606    20937     997
21  ben_Beng        SOV  0.8435    20937     997